import {
  Users,
  UserPlus,
  UserCheck,
  UserX,
  FileText,
  GraduationCap,
  Briefcase,
  UserRoundCog,
} from 'lucide-react';

export const dashboardChartStats = [
  {
    title: 'Current Employees',
    value: '6941',
    percentage: '+2.5%',
    description: 'Improved from last month',
    icon: Users,
    chartSeries: [{data: [10, 15, 12, 18, 20, 17, 22]}],
    chartColor: '#34d399',
  },
  {
    title: 'New Employees',
    value: '640',
    percentage: '+2.5%',
    description: 'Decreased from last month',
    icon: UserPlus,
    chartSeries: [{data: [20, 18, 15, 17, 13, 16, 18]}],
    chartColor: '#8b5cf6',
  },
  {
    title: 'Present Today',
    value: '580',
    percentage: '+5.0%',
    description: 'Increased from last month',
    icon: UserCheck,
    chartSeries: [{data: [10, 12, 15, 13, 17, 18, 16]}],
    chartColor: '#f59e0b',
  },
  {
    title: 'Absent Today',
    value: '-78',
    percentage: '-0.8%',
    description: 'Improved from last month',
    icon: UserX,
    chartSeries: [{data: [15, 12, 18, 10, 13, 11, 14]}],
    chartColor: '#ef4444',
  },

  {
    title: 'New CVs',
    value: '6941',
    percentage: '+2.5%',
    description: 'Improved from last month',
    icon: FileText,
    chartSeries: [{data: [10, 15, 12, 18, 20, 17, 22]}],
    chartColor: '#34d399',
  },
  {
    title: 'Intern Requests',
    value: '106',
    percentage: '+2.5%',
    description: 'Decreased from last month',
    icon: GraduationCap,
    chartSeries: [{data: [12, 15, 10, 17, 13, 16, 14]}],
    chartColor: '#6b7280',
  },
  {
    title: 'Running Interns',
    value: '580',
    percentage: '+5.0%',
    description: 'Increased from last month',
    icon: Briefcase,
    chartSeries: [{data: [10, 12, 15, 13, 17, 18, 16]}],
    chartColor: '#f59e0b',
  },
  {
    title: 'Intern to Employee',
    value: '640',
    percentage: '+2.5%',
    description: 'Improved from last month',
    icon: UserRoundCog,
    chartSeries: [{data: [20, 18, 15, 17, 13, 16, 18]}],
    chartColor: '#8b5cf6',
  },
];
